apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  # specifies number of pods to run
  replicas: 1
  # selector - find all pods with label 'client'
  selector:
    matchLabels:
      app: client
  # template - specify individual pod configuration
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: lambley/client:latest
# Cluster IP service (colocated)
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  # if not specified, Kubernetes defaults to Cluster IP service
  type: ClusterIP
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      # port for the NodePort
      port: 3000
      # port for internal redirection
      targetPort: 3000
