apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      # port for the NodePort
      port: 4000
      # port for internal redirection
      targetPort: 4000
